version: '3'
services:
  web:
    image: nginx
    #из локального копирует в гостевую
    volumes:
      - ./docker/conf/conf/default.conf:/etc/conf/nginx/default.conf
      - .:/var/www/html
    ports:
      - 8081:80
    restart: always
    depends_on:
      - php-fpm
      - db
  php-fpm:
    build: docker
    restart: always
    volumes:
      - ./docker/conf/php/xdebug.ini:/usr/local/etc/php/nginx/xdebug.ini
      - .:/var/www/html

  db:
    image: postgres:10.1
    #    volumes:
    #      - ./docker/postgres/data:/var/lib/postgresql/data
    restart: always
    environment:
      - POSTGRES_DB=dbname
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=dbpwd
    ports:
      - 54321:5432