<div class="white-box">
    <div class="t-container">
        <h1>404 - Not Found</h1>
        <p>The page you are looking for might have been removed or is temporarily unavailable.</p>
        <p>Please check the URL or go back to the <a href="/">homepage</a>.</p>
    </div>
</div>

<style>
    .white-box {
        background-color: #ffffff; /* Устанавливаем белый цвет фона */
        margin-top: 40px;
        margin-left: 40px;
        margin-right: 40px;
        padding: 20px; /* Добавляем внутренний отступ для контента */
        border: 2px solid #ffffff; /* Добавляем рамку черного цвета */
        border-radius: 30px; /* Добавляем скругленные углы */
    }

    .t-container {
    font-family: Arial, sans-serif;
    color: #212529;
    text-align: center;
    justify-content: center;
    }

    .t-container h1 {
    font-size: 3rem;
    margin-bottom: 20px;
    }

    .t-container p {
    font-size: 1.2rem;
    margin-bottom: 20px;
    }

    .t-container a {
    color: #007bff;
    text-decoration: none;
    font-weight: bold;
    }
</style>