<div class="container c-container">
    <h1 style="text-align: center; color: #1E262DFF;">Book Catalog</h1>

    <?php if (isset($books)) foreach ($books as $book):?>
        <div class="book">
            <img src="<?php echo $book->getImageUrl()?>" alt="Book 1">
            <h2><?php echo $book->getName() ?></h2>
            <p>Author: <?php echo $book->getAuthor() ?></p>
            <p>Year: <?php echo $book->getYear() ?></p>
            <p>Price: <?php echo $book->getPrice() ?></p>
            <p>Description: <?php echo $book->getDescription() ?></p>

            <form action="/catalog/add-to-cart" method="POST">
                <input type="hidden" name="book_id" value="<?php echo $book->getId() ?>">
                <button type="submit" class="add-to-cart-btn">Add to Cart</button>
            </form>
        </div>
    <?php endforeach ?>
</div>

<style>
    .c-container {
        margin-top: 40px;
        margin-left: 40px;
        margin-right: 40px;
    }

    .book {
        background-color: #fff;
        border-radius: 10px;
        padding: 20px;
        margin-bottom: 20px;
        box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
    }
    .book img {
        width: 10%;
        height: 10%;
        border-radius: 5px;
        margin-bottom: 10px;
    }
    .book h2 {
        font-size: 20px;
        margin-bottom: 10px;
    }
    .book p {
        color: #666;
    }

    .add-to-cart-btn {
        background-color: #1E262DFF;
        color: #fff;
        border: none;
        padding: 10px 20px;
        border-radius: 5px;
        cursor: pointer;
        transition: background-color 0.3s ease;
    }

    .add-to-cart-btn:hover {
        background-color: #0056b3;
    }
</style>