<div class="home-container">
    <div class="home-content">
        <h1>Welcome to our Website</h1>
        <img src="https://i.pinimg.com/originals/80/91/31/8091311bd91fb01d5b459cb51016d96f.jpg" alt="Banner">
        <h2>About Us</h2>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed eget justo nec libero tempor finibus eget sed quam. Maecenas quis fermentum lacus. Nullam in leo a risus viverra consectetur. Suspendisse potenti. Nam vel ultrices turpis, a interdum mauris.</p>
    </div>
    <div class="home-content">
        <h2>Our Services</h2>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed eget justo nec libero tempor finibus eget sed quam. Maecenas quis fermentum lacus. Nullam in leo a risus viverra consectetur. Suspendisse potenti. Nam vel ultrices turpis, a interdum mauris.</p>
        <ul>
            <li>Service 1</li>
            <li>Service 2</li>
            <li>Service 3</li>
        </ul>
    </div>
</div>

<style>
    body {
        font-family: Arial, sans-serif;
        background-color: #bdc3c7;
        color: #fff;
        margin: 0;
        padding: 0;
    }
    .home-container {
        max-width: 800px;
        margin: 50px auto;
        padding: 20px;
        background-color: #1E262D;
        border-radius: 8px;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
    }

    .home-container img {
        width: 50%;
        max-width: 400px
    }

    h1, h2, p {
        text-align: center;
        color: #fff;
    }
    /* Home styles */
    .home-content {
        margin-bottom: 20px;
    }
    .home-content h2 {
        font-size: 24px;
        font-weight: bold;
        margin-bottom: 10px;
    }
    .home-content p {
        font-size: 18px;
    }
    .home-content img {
        display: block;
        margin: 0 auto 20px;
        border-radius: 8px;
    }
</style>