<br>
<div class="l-container">
    <h1 style="text-align: center; color: #1E262DFF;">Login</h1>
    <p>Please fill in this form to log in.</p>
    <form action="/login" method="post">
        <label class="l-label" for="email"><b>Email</b></label>
        <?php if (isset($errors["user"])): ?>
            <label style="color: red"> <?php echo $errors["user"] ?></label>
        <?php endif; ?>
        <label class="l-label">
            <input type="text" placeholder="Enter Email" name="email" required>
        </label>

        <label class="l-label" for="psw"><b>Password</b></label>
        <?php if (isset($errors["password"])): ?>
            <label style="color: red"> <?php echo $errors["password"] ?></label>
        <?php endif; ?>
        <label class="l-label">
            <input type="password" placeholder="Enter Password" name="psw" required>
        </label>

        <button class="l-button" type="submit" style="font-family: Arial,serif;">Login</button>

        <label class="l-label">
            <input type="checkbox" id="remember" name="remember">
            <label for="remember">Remember me</label>
        </label>
    </form>
</div>

<div class="l-container">
    <form method="POST" action="/register">
        <label class="c-label">
            No account?
        </label>
        <button class="l-button" type="submit">Sign Up</button>
    </form>
</div>

<style>
    .c-label {
        text-align: center;
        margin: 120px;
        color: #1E262D;
    }

    .l-label {
        text-align: center;
        margin-bottom: 20px;
        color: #1E262D; /* черный цвет текста */
    }

    .l-container {
        max-width: 400px;
        margin: 50px auto;
        padding: 20px;
        background-color: #fff;
        border-radius: 8px;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
    }

    h1 {
        text-align: center;
        margin-bottom: 20px;
        color: #1E262D; /* черный цвет текста */
    }

    p {
        text-align: center;
        margin-bottom: 20px;
        color: #1E262D; /* черный цвет текста */
    }

    input[type="text"], input[type="password"] {
        width: 100%;
        padding: 15px;
        margin: 5px 0 22px 0;
        display: inline-block;
        border: none;
        background: #f1f1f1;
    }

    input[type="checkbox"] {
        display: none; /* Скрыть оригинальный чекбокс */
    }

    /* Стилизованный внешний вид замены для чекбокса */
    input[type="checkbox"] + label::before {
        content: '';
        display: inline-block;
        width: 20px; /* Задайте размер замены */
        height: 20px; /* Задайте размер замены */
        border: 1px solid #ccc;
        border-radius: 50%; /* Сделайте замену круглой */
        margin-right: 10px; /* Добавьте отступ между чекбоксом и текстом */
    }

    /* Стили при нажатии на чекбокс */
    input[type="checkbox"]:checked + label::before {
        background-color: #1E262DFF; /* Измените цвет фона при нажатии */
    }

    .l-button {
        font-family: Arial, sans-serif;
        font-style: revert;
        text-transform: uppercase;
        width: 100%;
        padding: 10px;
        margin-bottom: 10px;
        border: 1px solid #ccc;
        border-radius: 25px; /* Здесь задаём округлость кнопок */
        box-sizing: border-box;
        background-color: #1E262DFF;
        color: #fff;
        cursor: pointer;
    }

    .l-button:hover {
        background-color: #0056b3;
    }
</style>
