<div class="p-container">
    <h1>User Profile</h1>
    <div class="profile-info">
        <img src="avatar.jpg" alt="User Avatar">
        <p class="username"><?php if (isset($name)) echo $name ?></p>
        <p class="email"><?php if (isset($email)) echo $email ?></p>
    </div>
    <div class="edit-buttons">
        <form method="GET" action="/profile/edit">
        <button class="edit-btn">Edit Description</button>
        </form>

        <form method="GET" action="/profile/edit">
            <button class="edit-btn">Edit Avatar</button>
        </form>
    </div>
    <h2>About Me</h2>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed eget justo nec libero tempor finibus eget sed quam. Maecenas quis fermentum lacus. Nullam in leo a risus viverra consectetur. Suspendisse potenti. Nam vel ultrices turpis, a interdum mauris. Morbi sed odio et dui pharetra scelerisque a in nisi. Vivamus aliquet massa a leo convallis, id pharetra magna consectetur. Ut accumsan fringilla purus at laoreet. Nam accumsan id arcu a fringilla. Donec euismod odio nec lectus hendrerit ullamcorper. Etiam interdum arcu sit amet massa suscipit faucibus.</p>
</div>

<style>
    .edit-buttons {
        text-align: center;
        justify-content: normal;
    }

    .edit-btn {
        text-transform: uppercase;
        background-color: #ffffff;
        color: #1E262D;
        border: none;
        padding: 10px 20px;
        border-radius: 5px;
        cursor: pointer;
        transition: background-color 0.3s ease;
    }

    .edit-btn:hover {
        background-color: rgb(100, 100, 100);
    }

    .p-container {
        max-width: 800px;
        margin: 50px auto;
        padding: 20px;
        background-color: #1E262D;
        border-radius: 8px;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
    }
    h1, h2, p {
        text-align: center;
        color: #fff;
    }
    /* Profile styles */
    .profile-info {
        margin-bottom: 20px;
    }
    .profile-info img {
        width: 150px;
        height: 150px;
        border-radius: 50%;
        margin: 0 auto 20px;
        display: block;
    }
    .profile-info .username {
        font-size: 24px;
        font-weight: bold;
    }
    .profile-info .email {
        font-size: 18px;
    }
</style>