<div class="p-container">
    <h1>User Profile</h1>
    <div class="profile-info">
        <img src="<?php if (isset($avatar)) echo $avatar; else echo "https://media.moddb.com/images/games/1/71/70031/1img_311846.png" ?>" alt="User Avatar">
        <p class="username"><?php if (isset($name)) echo $name ?></p>
        <p class="email"><?php if (isset($email)) echo $email ?></p>
    </div>
    <div class="edit-buttons">
        <form method="GET" action="/profile/edit">
            <button class="edit-btn">Edit Description</button>
        </form>
        <form method="GET" action="/profile/edit">
            <button class="edit-btn">Edit Avatar</button>
        </form>
    </div>
    <h2>About Me</h2>
    <p>
        <?php if (isset($description)) echo $description ?>
    </p>
</div>

<style>
    .edit-buttons {
        display: flex; /* Размещаем кнопки в строку */
        justify-content: center; /* Выравниваем их по центру по горизонтали */
        margin-bottom: 20px; /* Добавляем немного отступа снизу */
    }

    .edit-buttons form {
        margin: 0 10px; /* Добавляем немного отступа между кнопками */
    }

    .edit-btn {
        width: 200px;
        resize: none;
        text-transform: uppercase;
        font-size: 17px;
        background-color: #ffffff;
        color: #1E262D;
        border: none;
        padding: 10px 20px;
        border-radius: 5px;
        cursor: pointer;
        transition: background-color 0.3s ease;
    }

    .edit-btn:hover {
        background-color: rgb(100, 100, 100);
    }

    .p-container {
        max-width: 800px;
        margin: 50px auto;
        padding: 20px;
        background-color: #1E262D;
        border-radius: 8px;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        text-align: center; /* Центрируем содержимое контейнера */
    }

    h1, h2, p {
        color: #fff;
    }

    .profile-info {
        margin-bottom: 20px;
    }
    .profile-info img {
        width: 150px;
        height: 150px;
        border-radius: 50%;
        margin: 0 auto 20px;
        display: block;
    }

    .profile-info .username {
        font-size: 24px;
        font-weight: bold;
    }
    .profile-info .email {
        font-size: 18px;
    }
</style>