<form method="POST" action="/register">
    <div class="l-container">
        <h1>Register</h1>
        <p>Please fill in this form to create an account.</p>
        <hr>

        <label class="l-label" for="name"><b>Name</b></label>
        <?php if (isset($errors) && $errors->hasKey("name")): ?>
            <label class="l-label error-label"> <?php echo $errors->getMessage("name"); ?></label>
        <?php endif; ?>
        <input type="text" placeholder="Enter Name" name="name" id="name" required>


        <label class="l-label" for="email"><b>Email</b></label>
        <?php if (isset($errors) && $errors->hasKey("email")): ?>
            <label class="l-label error-label"> <?php echo $errors->getMessage("email"); ?></label>
        <?php endif; ?>
        <input type="text" placeholder="Enter Email" name="email" id="email" required>

        <label class="l-label" for="psw"><b>Password</b></label>
        <?php if (isset($errors) && $errors->hasKey("password")): ?>
            <label class="l-label error-label"> <?php echo $errors->getMessage("password"); ?></label>
        <?php endif; ?>
        <label for="password"></label><input type="password" placeholder="Enter Password" name="password" id="password" required>

        <label class="l-label" for="psw-repeat"><b>Repeat Password</b></label>
        <label for="password-repeat"></label><input type="password" placeholder="Repeat Password" name="password-repeat" id="password-repeat" required>

        <button class="l-button" type="submit">Register</button>
    </div>
</form>

<div class="l-container">
    <form method="POST" action="/login">
        <label class="c-label">
            Already have an account?
        </label>
        <button class="l-button" type="submit">Sign In</button>
    </form>
</div>

<style>
    .c-label {
        text-align: center;
        margin: 55px;
        color: #1E262D;
    }

    .l-label {
        text-align: center;
        margin-bottom: 20px;
        color: #1E262D; /* черный цвет текста */
    }

    .error-label {
        color: rgb(255, 0, 0);
    }

    .l-container {
        max-width: 400px;
        margin: 50px auto;
        padding: 20px;
        background-color: #fff;
        border-radius: 8px;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
    }

    h1 {
        text-align: center;
        margin-bottom: 20px;
        color: #1E262D; /* черный цвет текста */
    }

    p {
        text-align: center;
        margin-bottom: 20px;
        color: #1E262D; /* черный цвет текста */
    }

    input[type="text"], input[type="password"] {
        width: 100%;
        padding: 15px;
        margin: 5px 0 22px 0;
        display: inline-block;
        border: none;
        background: #f1f1f1;
    }

    input[type="checkbox"] {
        display: none; /* Скрыть оригинальный чекбокс */
    }

    /* Стилизованный внешний вид замены для чекбокса */
    input[type="checkbox"] + label::before {
        content: '';
        display: inline-block;
        width: 20px; /* Задайте размер замены */
        height: 20px; /* Задайте размер замены */
        border: 1px solid #ccc;
        border-radius: 50%; /* Сделайте замену круглой */
        margin-right: 10px; /* Добавьте отступ между чекбоксом и текстом */
    }

    /* Стили при нажатии на чекбокс */
    input[type="checkbox"]:checked + label::before {
        background-color: #1E262DFF; /* Измените цвет фона при нажатии */
    }

    .l-button {
        font-family: Arial, sans-serif;
        font-style: revert;
        text-transform: uppercase;
        width: 100%;
        padding: 10px;
        margin-bottom: 10px;
        border: 1px solid #ccc;
        border-radius: 25px; /* Здесь задаём округлость кнопок */
        box-sizing: border-box;
        background-color: #1E262DFF;
        color: #fff;
        cursor: pointer;
    }

    .l-button:hover {
        background-color: #0056b3;
    }
</style>